### PR TITLE
(Fix) Replace on('receipt') with web3.eth.sendTransaction and fix #153

### LINKED ISSUE #153: (Bug) negative value of minutes in alert
screen shot 2018-07-12 at 13 00 08
screen shot 2018-07-12 at 13 00 22

### PR DESCRIPTION
**Pull request by varasev**
- (Mandatory) Description
These changes are for fixing issues https://github.com/poanetwork/poa-dapps-voting/issues/125 and https://github.com/poanetwork/poa-dapps-voting/issues/153. Must be merged after https://github.com/poanetwork/poa-dapps-voting/pull/157 is merged.

- (Mandatory) What is it: (Fix), (Feature) or (Refactor)
(Fix)

### CODE REVIEW

File: src/components/NewBallot.jsx [hunk 1]
```diff
@@ -242,26 +244,50 @@ export class NewBallot extends React.Component {
...
-          if (tx.status === true || tx.status === '0x1') {
-            const newId = Number(tx.events.BallotCreated.returnValues.id)
-            const card = await contractsStore.getCard(newId, contractType)
-            ballotsStore.ballotCards.push(card)
 
-            swal('Congratulations!', messages.BALLOT_CREATED_SUCCESS_MSG, 'success').then(result => {
-              push(`${commonStore.rootPath}`)
-              window.scrollTo(0, 0)
-            })
+      web3.eth.sendTransaction(
```
Comment (vbaranov) [inline src/components/NewBallot.jsx]: `web3.eth.sendTransaction` is defined 3 times with a similar code. Let's define the function in `src/helpers.js` and reuse it in components.

**Review by vbaranov — CHANGES_REQUESTED** [review]

File: src/components/NewBallot.jsx (hunk 1 above)
Comment (varasev) [reply src/components/NewBallot.jsx]: @vbaranov ok, I've done it in the last two commits: https://github.com/poanetwork/poa-dapps-voting/pull/158/commits/7fa26a17f1a5c29f7d63ee71e1f24858df4f99a9 and https://github.com/poanetwork/poa-dapps-voting/pull/158/commits/99a712f7d75e07553f66106f989edc3b80f5bf07. DApp was tested with `poa-test-setup` after these changes.

**Review by vbaranov — APPROVED** [review]
